name: quill_html_editor
description: HTML rich text editor for Android, iOS, and Web, it is built with the powerful Quill Js library. Which is an open source WYSIWYG editor built for the modern web.

version: 2.0.6-dev.3
homepage: https://github.com/the-airbender/quill_html_editor
repository: https://github.com/the-airbender/quill_html_editor
maintainer: Pavan Kumar Nagulavancha

environment:
  sdk: '>=2.18.1 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  webviewx_plus: ^0.3.2
  file_picker: ^5.2.2
  universal_io: ^2.0.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
      - packages/quill_html_editor/assets/camera_roll_icon.png
      - packages/quill_html_editor/assets/h1_dark.png
      - packages/quill_html_editor/assets/h2_dark.png
      - packages/quill_html_editor/assets/edit_table.png
      - packages/quill_html_editor/assets/insert_table.png
      - packages/quill_html_editor/assets/delete_column.png
      - packages/quill_html_editor/assets/delete_row.png
      - packages/quill_html_editor/assets/delete_table.png
      - packages/quill_html_editor/assets/insert_column_left.png
      - packages/quill_html_editor/assets/insert_row_above.png
      - packages/quill_html_editor/assets/insert_row_below.png
      - packages/quill_html_editor/assets/insert_column_right.png
