name: quill_html_editor
description: HTML rich text editor for Android, iOS and Web, using the QuilJS library.
version: 0.1.5
homepage: https://github.com/the-airbender/quill_html_editor
repository: https://github.com/the-airbender/quill_html_editor
maintainer: Pavan Kumar

environment:
  sdk: '>=2.18.1 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  webviewx: ^0.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
